name: CI

on:
  pull_request:
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          set +e
          false
          if [ $? -ne 0 ]; then
              exit 1234
          fi
          echo "SUCCESS"
