name: Dependabot

on:
  workflow_dispatch:

jobs:
  summary:
    name: Dependabot Update
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          echo '### ⚠️Warning⚠️' >> $GITHUB_STEP_SUMMARY
          echo 'Bundler 1 will be deprecated soon!' >> $GITHUB_STEP_SUMMARY

    
