name: Does Cache use Quota

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  does:
    name: Does Cache use Quota
    runs-on: ubuntu-latest
    steps:
      - name: Output current API quota
        run: |
          gh api "https://api.github.com/rate_limit" | jq .

      - name: Output current API quota again
        run: |
          gh api "https://api.github.com/rate_limit" | jq .

      - name: Use cache restore
        uses: actions/cache@v2
        with:
          path: does-not-exist
          key: does-not-exist

      - name: Output current API quota last time
        run: |
          gh api "https://api.github.com/rate_limit" | jq .
