# Runs all ecosystems cached and concurrently.
name: Smoke

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    paths-ignore:
      - docs/**
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dorny/paths-filter@v2
        if: github.event_name != 'workflow_dispatch'
        id: changes
        with:
          filters: |
            common:
              - .github/workflows/**
            client:
              - client/**

      - name: Echo the paths changed
        run: |
          echo "The following paths were changed:"
          echo "${{ toJson(steps.changes.outputs) }}"
