# Runs all ecosystems cached and concurrently.
name: Smoke

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    paths-ignore:
      - docs/**
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dorny/paths-filter@v2
        if: github.event_name != 'workflow_dispatch'
        id: changes
        with:
          filters: |
            common:
              - .github/workflows/**
            client:
              - client/**

      - name: Echo the paths changed
        run: |
          echo "The following paths were changed: ${{ toJson(steps.changes.outputs.changes) }}"
          # Write the changes.json file which is an array of paths
          echo "${{ toJson(steps.changes.outputs.changes) }}" > changes.json

      - name: Read matrix.json and filter by changes.json
        run: |
          # Read the matrix.json file which is an array of objects
          matrix=$(cat matrix.json)
          # Filter the matrix.json file by the changes.json file
          filtered=$(jq --argjson changes "$(cat changes.json)" '.[] | select(.paths | any($changes[]; contains(.)))' <<< "$matrix")
          # Output to GITHUB_OUTPUT
          echo "filtered=$filtered" >> $GITHUB_OUTPUT

  execute:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJson(needs.discover.outputs.filtered) }}
    steps:
      - name: Hello from ${{ matrix.suite }}
        run: |
          echo "Hello from ${{ matrix.suite }}"
