name: Outputs
on:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get workflow names
        id: suites
        run: |
          echo "suite=$(ls .github/workflows | sed 's/.yml$//' | jq -R | jq -sc)" >> $GITHUB_OUTPUT
    outputs:
        suites: ${{ steps.suites.outputs.suite }}
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Output workflow names
        run: |
          echo "Workflows: ${{ needs.first.outputs.suites }}"
          echo "fromJSON: ${{ fromJSON(needs.first.outputs.suites) }}"
  third:
    runs-on: ubuntu-latest
    needs: first
    strategy:
        matrix:
            suite: ${{ fromJSON(needs.first.outputs.suites) }}
    steps:
      - name: Run ${{ matrix.suite }}
        run: echo "Running ${{ matrix.suite }}"
