name: Outputs
on:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get workflow names
        id: suites
        run: |
          for f in $(ls .github/workflows | sed 's/.yml$//'); do
            echo "suite=$f" >> $GITHUB_STATE
          done
    outputs:
        suites: ${{ toJSON(steps.suites.outputs.suites) }}
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Output workflow names
        run: |
          echo "Workflows: ${{ fromJSON(needs.first.outputs.suites) }}
