name: Outputs
on:
  workflow_dispatch:
jobs:
  first:
    uses: jakecoffman/actions/.github/workflows/reusable.yml@main
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Output workflow names
        run: |
          echo "Workflows: ${{ needs.first.outputs.workflows }}"
          echo "fromJSON: ${{ fromJSON(needs.first.outputs.workflows) }}"
  third:
    runs-on: ubuntu-latest
    needs: first
    strategy:
        matrix:
            suite: ${{ fromJSON(needs.first.outputs.workflows) }}
    steps:
      - name: Run ${{ matrix.suite }}
        run: echo "Running ${{ matrix.suite }}"
