name: Pass Env Var
on:
  workflow_dispatch:
jobs:
  one:
    runs-on: ubuntu-latest
    outputs:
      FOO: ${{ steps.step1.outputs.FOO }}
    steps:
      - id: step1
        name: Set env var
        run: echo "FOO=bar" >> $GITHUB_OUTPUT
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: Get Env var
        run: echo "FOO is ${{ needs.one.outputs.FOO }}"
