name: Triggers

on:
  pull_request:
    - type:
        - edited
    - branches:
        - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "SUCCESS"

