name: CI

on:
  pull_request:
    - branches:
        - main
  pull_request_review:
    types:
      - submitted

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "SUCCESS"
